[package]
name = "sovd_server_comp"
version.workspace = true
edition.workspace = true

[dependencies]
opensovd-core = { workspace = true }
opensovd-server = { workspace = true }
uprotocol_log_client_comp = { workspace = true }
up-rust = { version = "0.9", default-features = false, features = ["communication", "util"] }
up-transport-zenoh = { workspace = true }
async-trait = { workspace = true }
chrono = { workspace = true }
serde_json = "1"
tokio = { workspace = true, features = ["full"] }
tracing = { workspace = true }
tracing-subscriber = { workspace = true, features = ["env-filter"] }
